adorgroup:
  mqtt:
    client:
      id: babycar_mqtt_dev
      receive:
        id: babycar_mqtt_receive_dev
    completionTimeout: 30000
    default:
      topic: babycar
    password: 6a311552210eff6d035bf7fe17fa3b6f
    url: tcp://www.ie-goal.cn:1883
    username: adorgroup
    productId: d0b75ae9f72a9665


spring:
  application:
    name: adorgroup-babycar-mqtt
  datasource:
    url: jdbc:mysql://139.196.208.236/babycar?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: iegoal123456
    druid:
      initial-size: 30
      max-active: 60
      min-idle: 2
      max-wait: 10
      WebStatFilter:
        exclusions: \*.js,\*.gif,\*.jpg,\*.png,\*.css,\*.ico,/druid/\*
      StatViewServlet:
        loginUsername: druid
        loginPassword: druid
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: true


server:
  port: 8092
  context-path: /
  tomcat:
    uri-encoding: UTF-8


mybatis:
  configuration:
    cache-enabled: false
    aggressive-lazy-loading: false
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: reuse
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: statement
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  path: E:/var/logs/babycar_mqtt
#  level:
#    com:
#      adorgroup:
#        babycar:
#          mqtt:
#            dao: debug

